baseURL = "https://ipfs.io"
relativeURLs = true
preserveTaxonomyNames = true
googleAnalytics = "UA-52930282-2"
disableRSS = true

[taxonomies]
  author = "author"

[params]
  domain = "ipfs.io"
  name = "PLANETCHAIN"
  title = "PLANETCHAIN is focusing on decentrallized web techonologies"
  description = "A Labs to provide services and applications based on IPFS and blockchain"
  author = "PLANETCHAIN"
  github = "https://github.com/planetchain"
  specifications = "https://github.com/ipfs/specs"
  social = [ { title = "Twitter", link = "http://twitter.com/ipfsbot" },
    { title = "Facebook", link = "https://www.facebook.com/sharer/sharer.php?u=https://ipfs.io" },
    { title = "Google", link = "https://plus.google.com/108638684245894749879" },
    { title = "YouTube", link = "https://www.youtube.com/channel/UCdjsUXJ3QawK4O5L1kqqsew" } ]
